(()=>{'use strict';
const KEY='janTrade.pro.v1',CURRENCY='USD';
const seed={accounts:[{id:'main',name:'Main Account',balance:10000}],playbooks:[{id:'pb-a',name:'A+ Liquidity Setup',market:'XAUUSD / NAS100',entry:'Liquidity sweep + SMT + CISD عند OB/FVG أو Session H/L',exit:'SL خلف آخر Swing، الهدف 2R–3R دون تحريك عشوائي',risk:'0.3%–0.5% لكل صفقة، توقف بعد خسارتين'}],trades:[]};
let state=load(),calendarDate=new Date(),range='all',deferredPrompt=null,currentImage='';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function clone(x){return JSON.parse(JSON.stringify(x))}function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x&&Array.isArray(x.trades)&&Array.isArray(x.accounts)&&Array.isArray(x.playbooks)?x:clone(seed)}catch{return clone(seed)}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch{toast('تعذر الحفظ: مساحة التخزين ممتلئة');return false}}
function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function money(n){return new Intl.NumberFormat('en-GB',{style:'currency',currency:CURRENCY,maximumFractionDigits:2}).format(Number(n)||0)}
function pnl(t){return +(Number(t.riskAmount||0)*Number(t.resultR||0)-Number(t.fees||0)).toFixed(2)}
function accountName(id){return state.accounts.find(a=>a.id===id)?.name||'محذوف'}
function selectedTrades(){const acc=$('#accountFilter').value;return state.trades.filter(t=>acc==='all'||t.accountId===acc)}
function metrics(list=selectedTrades()){const ts=[...list].sort((a,b)=>new Date(a.date)-new Date(b.date)),ps=ts.map(pnl),wins=ps.filter(x=>x>0),losses=ps.filter(x=>x<0),be=ps.filter(x=>x===0),gw=wins.reduce((a,b)=>a+b,0),gl=Math.abs(losses.reduce((a,b)=>a+b,0)),net=ps.reduce((a,b)=>a+b,0);let eq=0,peak=0,maxDD=0,streak=0,maxWinStreak=0,maxLossStreak=0,ls=0;const curve=[0];for(const p of ps){eq+=p;curve.push(eq);peak=Math.max(peak,eq);maxDD=Math.max(maxDD,peak-eq);if(p>0){streak++;ls=0;maxWinStreak=Math.max(maxWinStreak,streak)}else if(p<0){ls++;streak=0;maxLossStreak=Math.max(maxLossStreak,ls)}}const followed=ts.filter(t=>t.rulesFollowed==='yes').length;return{ts,ps,wins,losses,be,gw,gl,net,curve,maxDD,winRate:ts.length?wins.length/ts.length*100:0,pf:gl?gw/gl:(gw?Infinity:0),avgR:ts.length?ts.reduce((a,t)=>a+Number(t.resultR||0),0)/ts.length:0,expectancy:ts.length?net/ts.length:0,avgWin:wins.length?gw/wins.length:0,avgLoss:losses.length?-gl/losses.length:0,best:ps.length?Math.max(...ps):0,worst:ps.length?Math.min(...ps):0,maxWinStreak,maxLossStreak,discipline:ts.length?followed/ts.length*100:0}}
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2300)}
function stat(label,value,tone='',sub=''){return `<article class="stat"><div class="stat-label"><span>${label}</span></div><div class="stat-value ${tone}">${value}</div>${sub?`<div class="stat-sub">${sub}</div>`:''}</article>`}
function render(){fillSelects();renderDashboard();renderTrades();renderCalendar();renderAnalytics();renderPlaybooks();renderSettings()}
function fillSelects(){const af=$('#accountFilter'),cur=af.value||'all';af.innerHTML='<option value="all">كل الحسابات</option>'+state.accounts.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('');af.value=[...af.options].some(o=>o.value===cur)?cur:'all';$('#tradeAccount').innerHTML=state.accounts.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('');$('#setup').innerHTML='<option value="">بدون استراتيجية</option>'+state.playbooks.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}
function renderDashboard(){const list=selectedTrades(),m=metrics(list);$('#mainStats').innerHTML=stat('صافي الربح',money(m.net),m.net>0?'good':m.net<0?'bad':'cyan')+stat('معدل الفوز',m.winRate.toFixed(1)+'%','cyan',`${m.wins.length} رابحة / ${m.losses.length} خاسرة`)+stat('Profit Factor',m.pf===Infinity?'∞':m.pf.toFixed(2),m.pf>=1?'good':'bad')+stat('متوسط R',m.avgR.toFixed(2)+'R',m.avgR>0?'good':m.avgR<0?'bad':'')+stat('أقصى تراجع',money(-m.maxDD),'bad')+stat('عدد الصفقات',String(m.ts.length),'');$('#equityHint').textContent=`الحصيلة ${money(m.net)}`;drawEquity(m);const d=m.discipline;$('#qualityRing').style.background=`conic-gradient(var(--green) ${d*3.6}deg,var(--line) 0)`;$('#qualityRing b').textContent=d.toFixed(0)+'%';$('#qualityList').innerHTML=`<div class="mini-row"><span>صفقات ملتزمة</span><b>${m.ts.filter(t=>t.rulesFollowed==='yes').length}</b></div><div class="mini-row"><span>التزام جزئي</span><b>${m.ts.filter(t=>t.rulesFollowed==='partial').length}</b></div><div class="mini-row"><span>مخالفة القواعد</span><b class="bad">${m.ts.filter(t=>t.rulesFollowed==='no').length}</b></div>`;renderGroupBars('#topSetups',list,t=>state.playbooks.find(p=>p.id===t.setupId)?.name||'بدون استراتيجية',4);const recent=[...list].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,5);$('#recentTrades').innerHTML=recent.length?recent.map(t=>`<div class="recent-row"><div class="recent-main"><div class="symbol-icon">${esc(t.symbol.slice(0,3))}</div><span><b>${esc(t.symbol)}</b><br><small class="muted">${new Date(t.date).toLocaleDateString('ar-GB')}</small></span></div><b class="${pnl(t)>0?'good':pnl(t)<0?'bad':''}">${money(pnl(t))}</b></div>`).join(''):'<div class="empty">أضف أول صفقة لبدء التحليل.</div>'}
function drawEquity(m){let ts=m.ts;if(range!=='all'){const from=Date.now()-Number(range)*864e5;ts=ts.filter(t=>new Date(t.date).getTime()>=from)}const ps=ts.map(pnl),vals=[0];ps.forEach(p=>vals.push(vals.at(-1)+p));const svg=$('#equityChart'),w=900,h=300,pad={x:30,y:25},min=Math.min(...vals),max=Math.max(...vals),span=max-min||1;let grid='';for(let i=1;i<5;i++){const y=h*i/5;grid+=`<line class="gridline" x1="0" y1="${y}" x2="${w}" y2="${y}"/>`}if(vals.length<2){svg.innerHTML=grid+'<text x="450" y="150" text-anchor="middle">أضف أول صفقة لعرض المنحنى</text>';return}const pts=vals.map((v,i)=>[pad.x+i/(vals.length-1)*(w-pad.x*2),h-pad.y-(v-min)/span*(h-pad.y*2)]),path=pts.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+' '+p[1].toFixed(1)).join(' '),area=path+` L ${pts.at(-1)[0]} ${h-pad.y} L ${pad.x} ${h-pad.y} Z`;svg.innerHTML=`<defs><linearGradient id="areaGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#43dcff" stop-opacity=".28"/><stop offset="1" stop-color="#43dcff" stop-opacity="0"/></linearGradient></defs>${grid}<path class="area" d="${area}"/><path class="equity" d="${path}"/><text x="${w-8}" y="18" text-anchor="end">${money(max)}</text><text x="${w-8}" y="${h-4}" text-anchor="end">${money(min)}</text>`}
function resultKind(t){const p=pnl(t);return p>0?'win':p<0?'loss':'be'}
function filteredTrades(){const q=$('#tradeSearch').value.trim().toLowerCase(),rf=$('#resultFilter').value,sf=$('#sessionFilter').value;return selectedTrades().filter(t=>(!q||[t.symbol,t.notes,t.mistakes,state.playbooks.find(p=>p.id===t.setupId)?.name].join(' ').toLowerCase().includes(q))&&(rf==='all'||resultKind(t)===rf)&&(sf==='all'||t.session===sf)).sort((a,b)=>new Date(b.date)-new Date(a.date))}
function renderTrades(){const list=filteredTrades();$('#tradeEmpty').style.display=list.length?'none':'block';$('#tradeTable').innerHTML=list.map(t=>`<tr><td>${new Date(t.date).toLocaleString('ar-GB',{dateStyle:'short',timeStyle:'short'})}</td><td><b>${esc(t.symbol)}</b></td><td>${esc(accountName(t.accountId))}</td><td>${t.direction==='long'?'شراء ↑':'بيع ↓'}</td><td>${esc(t.session)}</td><td>${esc(state.playbooks.find(p=>p.id===t.setupId)?.name||'—')}</td><td class="${Number(t.resultR)>0?'good':Number(t.resultR)<0?'bad':''}">${Number(t.resultR).toFixed(2)}R</td><td class="${pnl(t)>0?'good':pnl(t)<0?'bad':''}">${money(pnl(t))}</td><td><span class="badge ${t.rulesFollowed==='yes'?'yes':t.rulesFollowed==='no'?'no':''}">${t.rulesFollowed==='yes'?'ملتزم':t.rulesFollowed==='partial'?'جزئي':'مخالفة'}</span></td><td><div class="row-actions"><button class="row-btn edit-trade" data-id="${t.id}">تعديل</button><button class="row-btn delete-trade" data-id="${t.id}">حذف</button></div></td></tr>`).join('');$$('.edit-trade').forEach(b=>b.onclick=()=>openTrade(b.dataset.id));$$('.delete-trade').forEach(b=>b.onclick=()=>{if(confirm('حذف هذه الصفقة؟')){state.trades=state.trades.filter(t=>t.id!==b.dataset.id);save();render();toast('تم حذف الصفقة')}})}
function renderCalendar(){const y=calendarDate.getFullYear(),mo=calendarDate.getMonth(),first=new Date(y,mo,1),start=new Date(y,mo,1-first.getDay());$('#calendarTitle').textContent=new Intl.DateTimeFormat('ar-GB',{month:'long',year:'numeric'}).format(first);const by={};selectedTrades().forEach(t=>{const k=t.date.slice(0,10);(by[k]??=[]).push(t)});let html='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const k=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-'),list=by[k]||[],sum=list.reduce((a,t)=>a+pnl(t),0),today=k===new Date().toISOString().slice(0,10);html+=`<div class="cal-day ${d.getMonth()!==mo?'muted':''} ${today?'today':''}"><span class="cal-num">${d.getDate()}</span>${list.length?`<b class="cal-pnl ${sum>0?'good':sum<0?'bad':''}">${money(sum)}</b><span class="cal-count">${list.length} صفقات</span>`:''}</div>`}$('#calendarGrid').innerHTML=html}
function group(list,key){const out={};list.forEach(t=>{const k=key(t)||'غير محدد';out[k]=(out[k]||0)+pnl(t)});return out}
function renderGroupBars(sel,list,key,limit=8){const entries=Object.entries(group(list,key)).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1])).slice(0,limit),max=Math.max(1,...entries.map(x=>Math.abs(x[1])));$(sel).innerHTML=entries.length?entries.map(([k,v])=>`<div><div class="bar-top"><b>${esc(k)}</b><span class="${v>0?'good':v<0?'bad':''}">${money(v)}</span></div><div class="bar-track"><div class="bar-fill ${v<0?'loss':''}" style="width:${Math.abs(v)/max*100}%"></div></div></div>`).join(''):'<div class="empty">لا توجد بيانات كافية.</div>'}
function renderAnalytics(){const list=selectedTrades(),m=metrics(list);$('#advancedStats').innerHTML=stat('التوقع لكل صفقة',money(m.expectancy),m.expectancy>0?'good':'bad')+stat('متوسط الربح',money(m.avgWin),'good')+stat('متوسط الخسارة',money(m.avgLoss),'bad')+stat('أفضل صفقة',money(m.best),'good')+stat('أسوأ صفقة',money(m.worst),'bad')+stat('أطول سلسلة فوز',String(m.maxWinStreak),'cyan');renderGroupBars('#sessionBars',list,t=>t.session);const days=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];renderGroupBars('#dayBars',list,t=>days[new Date(t.date).getDay()]);renderGroupBars('#symbolBars',list,t=>t.symbol);const mistakes=[];list.forEach(t=>String(t.mistakes||'').split(',').map(x=>x.trim()).filter(Boolean).forEach(x=>mistakes.push({...t,_m:x})));renderGroupBars('#mistakeBars',mistakes,t=>t._m)}
function renderPlaybooks(){const list=selectedTrades();$('#playbookGrid').innerHTML=state.playbooks.length?state.playbooks.map(p=>{const ts=list.filter(t=>t.setupId===p.id),m=metrics(ts);return `<article class="pb-card"><div class="panel-head"><div><h3>${esc(p.name)}</h3><small class="muted">${esc(p.market||'كل الأسواق')}</small></div><button class="row-btn delete-pb" data-id="${p.id}">حذف</button></div><p>${esc(p.entry)}</p><div class="pb-metrics"><div><span>الصفقات</span><b>${ts.length}</b></div><div><span>الفوز</span><b>${m.winRate.toFixed(0)}%</b></div><div><span>صافي P&L</span><b class="${m.net>0?'good':m.net<0?'bad':''}">${money(m.net)}</b></div></div><details><summary>القواعد</summary><p><b>الخروج:</b> ${esc(p.exit||'—')}<br><b>المخاطرة:</b> ${esc(p.risk||'—')}</p></details></article>`}).join(''):'<div class="empty">أنشئ أول استراتيجية لقياس أدائها.</div>';$$('.delete-pb').forEach(b=>b.onclick=()=>{if(state.trades.some(t=>t.setupId===b.dataset.id)){toast('لا يمكن حذف استراتيجية مرتبطة بصفقات');return}if(confirm('حذف الاستراتيجية؟')){state.playbooks=state.playbooks.filter(p=>p.id!==b.dataset.id);save();render()}})}
function renderSettings(){$('#accountList').innerHTML=state.accounts.map(a=>{const ts=state.trades.filter(t=>t.accountId===a.id),net=ts.reduce((s,t)=>s+pnl(t),0);return `<div class="settings-row"><span><b>${esc(a.name)}</b><br><small class="muted">ابتدائي ${money(a.balance)} · حالي ${money(a.balance+net)}</small></span>${a.id!=='main'?`<button class="row-btn delete-account" data-id="${a.id}">حذف</button>`:''}</div>`}).join('');$$('.delete-account').forEach(b=>b.onclick=()=>{if(state.trades.some(t=>t.accountId===b.dataset.id)){toast('لا يمكن حذف حساب يحتوي صفقات');return}state.accounts=state.accounts.filter(a=>a.id!==b.dataset.id);save();render()})}
function dtLocal(){const d=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return d.toISOString().slice(0,16)}
function openTrade(tradeId){if(!state.accounts.length){toast('أضف حسابًا أولًا');go('settings');return}const t=state.trades.find(x=>x.id===tradeId);$('#tradeForm').reset();$('#tradeId').value=t?.id||'';$('#tradeModalTitle').textContent=t?'تعديل الصفقة':'إضافة صفقة';$('#tradeAccount').value=t?.accountId||state.accounts[0].id;$('#tradeDate').value=t?.date||dtLocal();$('#symbol').value=t?.symbol||'';$('#direction').value=t?.direction||'long';$('#session').value=t?.session||'نيويورك';$('#setup').value=t?.setupId||'';['entry','stop','exit','size','riskAmount','resultR','fees'].forEach(k=>$('#'+k).value=t?.[k]??(k==='fees'?0:''));$('#grade').value=t?.grade||'A+';$('#emotion').value=t?.emotion||'هادئ';$('#rulesFollowed').value=t?.rulesFollowed||'yes';$('#mistakes').value=t?.mistakes||'';$('#notes').value=t?.notes||'';currentImage=t?.screenshot||'';$('#imageStatus').textContent=currentImage?'صورة محفوظة':'اختياري';calc();$('#tradeDialog').showModal()}
function calc(){$('#calculatedPnl').textContent=money((Number($('#riskAmount').value)||0)*(Number($('#resultR').value)||0)-(Number($('#fees').value)||0))}
async function fileData(file){if(!file)return'';if(file.size>1500000)throw Error('الصورة أكبر من 1.5MB');return new Promise((res,rej)=>{const r=new FileReader;r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function csvExport(){const h=['date','symbol','account','direction','session','setup','riskAmount','resultR','fees','pnl','grade','emotion','rulesFollowed','mistakes','notes'],rows=state.trades.map(t=>[t.date,t.symbol,accountName(t.accountId),t.direction,t.session,state.playbooks.find(p=>p.id===t.setupId)?.name||'',t.riskAmount,t.resultR,t.fees,pnl(t),t.grade,t.emotion,t.rulesFollowed,t.mistakes,t.notes]);download('jan-trade-'+new Date().toISOString().slice(0,10)+'.csv','\uFEFF'+[h,...rows].map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n'),'text/csv;charset=utf-8')}
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function go(page){$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===page));$$('.page').forEach(p=>p.classList.toggle('active',p.id===page+'Page'));const meta={dashboard:['لوحة الأداء','قرارات أوضح. تداول منضبط.'],trades:['سجل الصفقات','راجع كل تنفيذ بالتفصيل.'],calendar:['تقويم الأداء','شاهد أيام القوة والضعف.'],analytics:['التحليلات المتقدمة','اكتشف أين توجد ميزتك الحقيقية.'],playbooks:['الاستراتيجيات','قواعد قابلة للقياس، لا انطباعات.'],settings:['الإعدادات','الحسابات والنسخ الاحتياطي والتثبيت.']}[page];$('#pageTitle').textContent=meta[0];$('#pageSub').textContent=meta[1];scrollTo({top:0,behavior:'smooth'})}
$('#nav').onclick=e=>{const b=e.target.closest('.nav');if(b)go(b.dataset.page)};$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#addTradeBtn').onclick=$('#mobileAdd').onclick=()=>openTrade();$('#addPlaybookBtn').onclick=()=>{$('#playbookForm').reset();$('#playbookDialog').showModal()};$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());['riskAmount','resultR','fees'].forEach(k=>$('#'+k).oninput=calc);$('#screenshot').onchange=async e=>{try{currentImage=await fileData(e.target.files[0]);$('#imageStatus').textContent='تمت إضافة الصورة'}catch(err){currentImage='';e.target.value='';toast(err.message)}};
$('#tradeForm').addEventListener('submit',e=>{if(e.submitter?.value!=='save')return;e.preventDefault();const tid=$('#tradeId').value||id(),trade={id:tid,accountId:$('#tradeAccount').value,date:$('#tradeDate').value,symbol:$('#symbol').value.trim().toUpperCase(),direction:$('#direction').value,session:$('#session').value,setupId:$('#setup').value,entry:Number($('#entry').value)||null,stop:Number($('#stop').value)||null,exit:Number($('#exit').value)||null,size:Number($('#size').value)||null,riskAmount:Number($('#riskAmount').value),resultR:Number($('#resultR').value),fees:Number($('#fees').value)||0,grade:$('#grade').value,emotion:$('#emotion').value,rulesFollowed:$('#rulesFollowed').value,mistakes:$('#mistakes').value.trim(),notes:$('#notes').value.trim(),screenshot:currentImage};if(!trade.symbol||!trade.date||!trade.accountId||!(trade.riskAmount>0)||!Number.isFinite(trade.resultR)){toast('أكمل الحقول المطلوبة');return}const i=state.trades.findIndex(t=>t.id===tid);i>=0?state.trades[i]=trade:state.trades.push(trade);if(save()){$('#tradeDialog').close();render();toast(i>=0?'تم تحديث الصفقة':'تم حفظ الصفقة')}});
$('#playbookForm').addEventListener('submit',e=>{if(e.submitter?.value!=='save')return;e.preventDefault();state.playbooks.push({id:id(),name:$('#pbName').value.trim(),market:$('#pbMarket').value.trim(),entry:$('#pbEntry').value.trim(),exit:$('#pbExit').value.trim(),risk:$('#pbRisk').value.trim()});save();$('#playbookDialog').close();render();toast('تم إنشاء الاستراتيجية')});
$('#accountForm').onsubmit=e=>{e.preventDefault();state.accounts.push({id:id(),name:$('#accountName').value.trim(),balance:Number($('#accountBalance').value)});save();e.target.reset();render();toast('تمت إضافة الحساب')};$('#accountFilter').onchange=render;['tradeSearch','resultFilter','sessionFilter'].forEach(k=>$('#'+k).addEventListener(k==='tradeSearch'?'input':'change',renderTrades));$$('[data-range]').forEach(b=>b.onclick=()=>{$$('[data-range]').forEach(x=>x.classList.toggle('active',x===b));range=b.dataset.range;drawEquity(metrics())});$('#prevMonth').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar()};$('#nextMonth').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar()};
$('#csvExportBtn').onclick=csvExport;$('#csvImportBtn').onclick=()=>$('#csvFile').click();$('#csvFile').onchange=async e=>{try{const rows=parseCSV(await e.target.files[0].text());if(rows.length<2)throw Error('فارغ');const h=rows[0].map(x=>x.trim().toLowerCase()),idx=k=>h.indexOf(k),required=['date','symbol','riskamount','resultr'];if(required.some(k=>idx(k)<0))throw Error('يجب أن يحتوي CSV على date, symbol, riskAmount, resultR');let count=0;rows.slice(1).forEach(r=>{if(!r[idx('date')]||!r[idx('symbol')])return;state.trades.push({id:id(),accountId:state.accounts[0].id,date:r[idx('date')],symbol:r[idx('symbol')].toUpperCase(),direction:r[idx('direction')]||'long',session:r[idx('session')]||'نيويورك',setupId:'',riskAmount:Number(r[idx('riskamount')]),resultR:Number(r[idx('resultr')]),fees:idx('fees')>=0?Number(r[idx('fees')])||0:0,grade:'B',emotion:'هادئ',rulesFollowed:'yes',mistakes:'',notes:''});count++});save();render();toast(`تم استيراد ${count} صفقة`)}catch(err){toast(err.message||'ملف CSV غير صالح')}e.target.value=''};
$('#backupBtn').onclick=()=>download('jan-trade-backup-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(state),'application/json');$('#restoreBtn').onclick=()=>$('#restoreFile').click();$('#restoreFile').onchange=async e=>{try{const x=JSON.parse(await e.target.files[0].text());if(!Array.isArray(x.trades)||!Array.isArray(x.accounts)||!Array.isArray(x.playbooks))throw Error();if(confirm('استبدال البيانات الحالية بالنسخة؟')){state=x;save();render();toast('تمت استعادة النسخة')}}catch{toast('النسخة غير صالحة')}e.target.value=''};$('#wipeBtn').onclick=()=>{if(confirm('سيتم حذف كل الصفقات والحسابات نهائيًا. متابعة؟')){state=clone(seed);save();render();toast('تم حذف البيانات')}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true}};if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});render();
})();
